// Code generated by protoc-gen-go. DO NOT EDIT.
// source: authentication.proto

/*
Package authentication is a generated protocol buffer package.

It is generated from these files:
	authentication.proto

It has these top-level messages:
	CreateAccessTokenRequest
	CreateAccessTokenResponse
	DeleteAccessTokensRequest
	DeleteAccessTokensResponse
	AuthenticationRequest
	AuthenticationResponse
	Error
	SimpleResponse
*/
package authentication

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateAccessTokenRequest struct {
	ClientID string `protobuf:"bytes,1,opt,name=clientID" json:"clientID,omitempty"`
}

func (m *CreateAccessTokenRequest) Reset()                    { *m = CreateAccessTokenRequest{} }
func (m *CreateAccessTokenRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateAccessTokenRequest) ProtoMessage()               {}
func (*CreateAccessTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreateAccessTokenRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

type CreateAccessTokenResponse struct {
	Success     bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	AccessToken string `protobuf:"bytes,2,opt,name=accessToken" json:"accessToken,omitempty"`
	Error       *Error `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
}

func (m *CreateAccessTokenResponse) Reset()                    { *m = CreateAccessTokenResponse{} }
func (m *CreateAccessTokenResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateAccessTokenResponse) ProtoMessage()               {}
func (*CreateAccessTokenResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateAccessTokenResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *CreateAccessTokenResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *CreateAccessTokenResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type DeleteAccessTokensRequest struct {
	ClientID string `protobuf:"bytes,1,opt,name=clientID" json:"clientID,omitempty"`
}

func (m *DeleteAccessTokensRequest) Reset()                    { *m = DeleteAccessTokensRequest{} }
func (m *DeleteAccessTokensRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteAccessTokensRequest) ProtoMessage()               {}
func (*DeleteAccessTokensRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DeleteAccessTokensRequest) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

type DeleteAccessTokensResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Error   *Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *DeleteAccessTokensResponse) Reset()                    { *m = DeleteAccessTokensResponse{} }
func (m *DeleteAccessTokensResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteAccessTokensResponse) ProtoMessage()               {}
func (*DeleteAccessTokensResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeleteAccessTokensResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *DeleteAccessTokensResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type AuthenticationRequest struct {
	AccessToken string `protobuf:"bytes,1,opt,name=accessToken" json:"accessToken,omitempty"`
}

func (m *AuthenticationRequest) Reset()                    { *m = AuthenticationRequest{} }
func (m *AuthenticationRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthenticationRequest) ProtoMessage()               {}
func (*AuthenticationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AuthenticationRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type AuthenticationResponse struct {
	Success  bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	ClientID string `protobuf:"bytes,2,opt,name=clientID" json:"clientID,omitempty"`
	Error    *Error `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
}

func (m *AuthenticationResponse) Reset()                    { *m = AuthenticationResponse{} }
func (m *AuthenticationResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthenticationResponse) ProtoMessage()               {}
func (*AuthenticationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AuthenticationResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *AuthenticationResponse) GetClientID() string {
	if m != nil {
		return m.ClientID
	}
	return ""
}

func (m *AuthenticationResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Error struct {
	ErrorCode   string `protobuf:"bytes,1,opt,name=errorCode" json:"errorCode,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Error) GetErrorCode() string {
	if m != nil {
		return m.ErrorCode
	}
	return ""
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type SimpleResponse struct {
	Success bool   `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	Error   *Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *SimpleResponse) Reset()                    { *m = SimpleResponse{} }
func (m *SimpleResponse) String() string            { return proto.CompactTextString(m) }
func (*SimpleResponse) ProtoMessage()               {}
func (*SimpleResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SimpleResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *SimpleResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateAccessTokenRequest)(nil), "authentication.CreateAccessTokenRequest")
	proto.RegisterType((*CreateAccessTokenResponse)(nil), "authentication.CreateAccessTokenResponse")
	proto.RegisterType((*DeleteAccessTokensRequest)(nil), "authentication.DeleteAccessTokensRequest")
	proto.RegisterType((*DeleteAccessTokensResponse)(nil), "authentication.DeleteAccessTokensResponse")
	proto.RegisterType((*AuthenticationRequest)(nil), "authentication.AuthenticationRequest")
	proto.RegisterType((*AuthenticationResponse)(nil), "authentication.AuthenticationResponse")
	proto.RegisterType((*Error)(nil), "authentication.Error")
	proto.RegisterType((*SimpleResponse)(nil), "authentication.SimpleResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Authentication service

type AuthenticationClient interface {
	Authenticate(ctx context.Context, in *AuthenticationRequest, opts ...grpc.CallOption) (*AuthenticationResponse, error)
	CreateAccessToken(ctx context.Context, in *CreateAccessTokenRequest, opts ...grpc.CallOption) (*CreateAccessTokenResponse, error)
	DeleteAccessTokens(ctx context.Context, in *DeleteAccessTokensRequest, opts ...grpc.CallOption) (*DeleteAccessTokensResponse, error)
}

type authenticationClient struct {
	cc *grpc.ClientConn
}

func NewAuthenticationClient(cc *grpc.ClientConn) AuthenticationClient {
	return &authenticationClient{cc}
}

func (c *authenticationClient) Authenticate(ctx context.Context, in *AuthenticationRequest, opts ...grpc.CallOption) (*AuthenticationResponse, error) {
	out := new(AuthenticationResponse)
	err := grpc.Invoke(ctx, "/authentication.Authentication/Authenticate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationClient) CreateAccessToken(ctx context.Context, in *CreateAccessTokenRequest, opts ...grpc.CallOption) (*CreateAccessTokenResponse, error) {
	out := new(CreateAccessTokenResponse)
	err := grpc.Invoke(ctx, "/authentication.Authentication/CreateAccessToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authenticationClient) DeleteAccessTokens(ctx context.Context, in *DeleteAccessTokensRequest, opts ...grpc.CallOption) (*DeleteAccessTokensResponse, error) {
	out := new(DeleteAccessTokensResponse)
	err := grpc.Invoke(ctx, "/authentication.Authentication/DeleteAccessTokens", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Authentication service

type AuthenticationServer interface {
	Authenticate(context.Context, *AuthenticationRequest) (*AuthenticationResponse, error)
	CreateAccessToken(context.Context, *CreateAccessTokenRequest) (*CreateAccessTokenResponse, error)
	DeleteAccessTokens(context.Context, *DeleteAccessTokensRequest) (*DeleteAccessTokensResponse, error)
}

func RegisterAuthenticationServer(s *grpc.Server, srv AuthenticationServer) {
	s.RegisterService(&_Authentication_serviceDesc, srv)
}

func _Authentication_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authentication.Authentication/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).Authenticate(ctx, req.(*AuthenticationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authentication_CreateAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccessTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).CreateAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authentication.Authentication/CreateAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).CreateAccessToken(ctx, req.(*CreateAccessTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Authentication_DeleteAccessTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccessTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthenticationServer).DeleteAccessTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authentication.Authentication/DeleteAccessTokens",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthenticationServer).DeleteAccessTokens(ctx, req.(*DeleteAccessTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Authentication_serviceDesc = grpc.ServiceDesc{
	ServiceName: "authentication.Authentication",
	HandlerType: (*AuthenticationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _Authentication_Authenticate_Handler,
		},
		{
			MethodName: "CreateAccessToken",
			Handler:    _Authentication_CreateAccessToken_Handler,
		},
		{
			MethodName: "DeleteAccessTokens",
			Handler:    _Authentication_DeleteAccessTokens_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authentication.proto",
}

func init() { proto.RegisterFile("authentication.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xdf, 0xe4, 0xa5, 0xda, 0x4e, 0xa5, 0xe0, 0x60, 0x25, 0x0d, 0x1e, 0xca, 0x82, 0x52,
	0x15, 0x7a, 0xa8, 0xa0, 0x78, 0x2c, 0xad, 0x88, 0xd7, 0x28, 0x78, 0x94, 0xb8, 0x1d, 0x30, 0xda,
	0x66, 0xe3, 0xee, 0xf6, 0xe4, 0xd5, 0x8f, 0xe7, 0x87, 0x92, 0x6e, 0x4d, 0x9a, 0x7f, 0x25, 0x11,
	0x3c, 0xce, 0xb3, 0xf3, 0xcc, 0xfe, 0x66, 0x76, 0x12, 0x38, 0xf0, 0x97, 0xfa, 0x85, 0x42, 0x1d,
	0x70, 0x5f, 0x07, 0x22, 0x1c, 0x46, 0x52, 0x68, 0x81, 0x9d, 0xac, 0xca, 0x2e, 0xc1, 0x99, 0x48,
	0xf2, 0x35, 0x8d, 0x39, 0x27, 0xa5, 0x1e, 0xc4, 0x1b, 0x85, 0x1e, 0xbd, 0x2f, 0x49, 0x69, 0x74,
	0xa1, 0xc9, 0xe7, 0x01, 0x85, 0xfa, 0x6e, 0xea, 0x58, 0x7d, 0x6b, 0xd0, 0xf2, 0x92, 0x98, 0x7d,
	0x5a, 0xd0, 0x2b, 0x31, 0xaa, 0x48, 0x84, 0x8a, 0xd0, 0x81, 0x5d, 0xb5, 0x34, 0xba, 0x31, 0x36,
	0xbd, 0x38, 0xc4, 0x3e, 0xb4, 0xfd, 0x8d, 0xc1, 0xb1, 0x4d, 0xd9, 0xb4, 0x84, 0xe7, 0xd0, 0x20,
	0x29, 0x85, 0x74, 0xfe, 0xf7, 0xad, 0x41, 0x7b, 0xd4, 0x1d, 0xe6, 0xfa, 0xb8, 0x59, 0x1d, 0x7a,
	0xeb, 0x1c, 0x76, 0x05, 0xbd, 0x29, 0xcd, 0x29, 0x43, 0xa1, 0xea, 0xf0, 0x73, 0x70, 0xcb, 0x8c,
	0x95, 0xfc, 0x09, 0x9d, 0x5d, 0x83, 0xee, 0x1a, 0xba, 0xe3, 0xcc, 0x71, 0x4c, 0x96, 0x9b, 0x82,
	0x55, 0x98, 0x02, 0xfb, 0x80, 0xc3, 0xbc, 0xb5, 0x92, 0x2d, 0xdd, 0xaf, 0x9d, 0xed, 0xf7, 0x77,
	0x53, 0xbd, 0x85, 0x86, 0x89, 0xf1, 0x08, 0x5a, 0x46, 0x99, 0x88, 0x19, 0xfd, 0x50, 0x6e, 0x84,
	0x55, 0x17, 0x33, 0x52, 0x5c, 0x06, 0xd1, 0xaa, 0x44, 0xfc, 0x96, 0x29, 0x89, 0x3d, 0x42, 0xe7,
	0x3e, 0x58, 0x44, 0x73, 0xfa, 0xe3, 0xc9, 0x8e, 0xbe, 0x6c, 0xe8, 0x64, 0xe7, 0x83, 0x4f, 0xb0,
	0x97, 0x52, 0x08, 0x8f, 0xf3, 0x05, 0x4a, 0x9f, 0xc2, 0x3d, 0xa9, 0x4a, 0x5b, 0x83, 0xb3, 0x7f,
	0xf8, 0x0a, 0xfb, 0x85, 0x8d, 0xc7, 0x41, 0xde, 0xbe, 0xed, 0x6b, 0x72, 0x4f, 0x6b, 0x64, 0x26,
	0x77, 0x2d, 0x00, 0x8b, 0xeb, 0x89, 0x85, 0x12, 0x5b, 0x77, 0xdf, 0x3d, 0xab, 0x93, 0x1a, 0x5f,
	0xf7, 0xbc, 0x63, 0x7e, 0x0e, 0x17, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xeb, 0xd0, 0xfa, 0x52,
	0x34, 0x04, 0x00, 0x00,
}
